//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18010
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RoboPath.PlannerApp.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1600")]
        public int WorkspaceWidth {
            get {
                return ((int)(this["WorkspaceWidth"]));
            }
            set {
                this["WorkspaceWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1200")]
        public int WorkspaceHeight {
            get {
                return ((int)(this["WorkspaceHeight"]));
            }
            set {
                this["WorkspaceHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public double GeometryEditToolVertexRadius {
            get {
                return ((double)(this["GeometryEditToolVertexRadius"]));
            }
            set {
                this["GeometryEditToolVertexRadius"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public double DrawingVertexRadius {
            get {
                return ((double)(this["DrawingVertexRadius"]));
            }
            set {
                this["DrawingVertexRadius"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public double RobotBodyCircleMinRadius {
            get {
                return ((double)(this["RobotBodyCircleMinRadius"]));
            }
            set {
                this["RobotBodyCircleMinRadius"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("30")]
        public double RobotBodyCircleRadius {
            get {
                return ((double)(this["RobotBodyCircleRadius"]));
            }
            set {
                this["RobotBodyCircleRadius"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("200")]
        public double RobotBodyCircleMaxRadius {
            get {
                return ((double)(this["RobotBodyCircleMaxRadius"]));
            }
            set {
                this["RobotBodyCircleMaxRadius"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public double DrawingGoalVertexRadius {
            get {
                return ((double)(this["DrawingGoalVertexRadius"]));
            }
            set {
                this["DrawingGoalVertexRadius"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public double DrawingStartVertexRadius {
            get {
                return ((double)(this["DrawingStartVertexRadius"]));
            }
            set {
                this["DrawingStartVertexRadius"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("30")]
        public double RobotBodyCyclicPolygonRadius {
            get {
                return ((double)(this["RobotBodyCyclicPolygonRadius"]));
            }
            set {
                this["RobotBodyCyclicPolygonRadius"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public double RobotBodyCyclicPolygonMinRadius {
            get {
                return ((double)(this["RobotBodyCyclicPolygonMinRadius"]));
            }
            set {
                this["RobotBodyCyclicPolygonMinRadius"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("200")]
        public double RobotBodyCyclicPolygonMaxRadius {
            get {
                return ((double)(this["RobotBodyCyclicPolygonMaxRadius"]));
            }
            set {
                this["RobotBodyCyclicPolygonMaxRadius"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("6")]
        public int RobotBodyCyclicPolygonEdgeCount {
            get {
                return ((int)(this["RobotBodyCyclicPolygonEdgeCount"]));
            }
            set {
                this["RobotBodyCyclicPolygonEdgeCount"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public int RobotBodyCyclicPolygonMinEdgeCount {
            get {
                return ((int)(this["RobotBodyCyclicPolygonMinEdgeCount"]));
            }
            set {
                this["RobotBodyCyclicPolygonMinEdgeCount"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("32")]
        public int RobotBodyCyclicPolygonMaxEdgeCount {
            get {
                return ((int)(this["RobotBodyCyclicPolygonMaxEdgeCount"]));
            }
            set {
                this["RobotBodyCyclicPolygonMaxEdgeCount"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool IsGeometryVerticesVisible {
            get {
                return ((bool)(this["IsGeometryVerticesVisible"]));
            }
            set {
                this["IsGeometryVerticesVisible"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("8")]
        public int CircleEdgeCount {
            get {
                return ((int)(this["CircleEdgeCount"]));
            }
            set {
                this["CircleEdgeCount"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool IsObstacleDecompositionVisible {
            get {
                return ((bool)(this["IsObstacleDecompositionVisible"]));
            }
            set {
                this["IsObstacleDecompositionVisible"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool EnforceConvexRobotBody {
            get {
                return ((bool)(this["EnforceConvexRobotBody"]));
            }
            set {
                this["EnforceConvexRobotBody"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("200")]
        public int RobotPreviewCanvasWidth {
            get {
                return ((int)(this["RobotPreviewCanvasWidth"]));
            }
            set {
                this["RobotPreviewCanvasWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("200")]
        public int RobotPreviewCanvasHeight {
            get {
                return ((int)(this["RobotPreviewCanvasHeight"]));
            }
            set {
                this["RobotPreviewCanvasHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public double DrawingShortestPathVertexRadius {
            get {
                return ((double)(this["DrawingShortestPathVertexRadius"]));
            }
            set {
                this["DrawingShortestPathVertexRadius"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AlgorithmApplyDelaunayPathRefinement {
            get {
                return ((bool)(this["AlgorithmApplyDelaunayPathRefinement"]));
            }
            set {
                this["AlgorithmApplyDelaunayPathRefinement"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20")]
        public double AlgorithmVoronoiSampleDistance {
            get {
                return ((double)(this["AlgorithmVoronoiSampleDistance"]));
            }
            set {
                this["AlgorithmVoronoiSampleDistance"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("8")]
        public double DrawingSpecialVertexRadius {
            get {
                return ((double)(this["DrawingSpecialVertexRadius"]));
            }
            set {
                this["DrawingSpecialVertexRadius"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AlgorithmVisibilityGraphIncludeBoundary {
            get {
                return ((bool)(this["AlgorithmVisibilityGraphIncludeBoundary"]));
            }
            set {
                this["AlgorithmVisibilityGraphIncludeBoundary"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AlgorithmVisibilityGraphStopOnGoalVertexDiscovery {
            get {
                return ((bool)(this["AlgorithmVisibilityGraphStopOnGoalVertexDiscovery"]));
            }
            set {
                this["AlgorithmVisibilityGraphStopOnGoalVertexDiscovery"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool AlgorithmTriangulationUseSleeveOptimization {
            get {
                return ((bool)(this["AlgorithmTriangulationUseSleeveOptimization"]));
            }
            set {
                this["AlgorithmTriangulationUseSleeveOptimization"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50")]
        public double AlgorithmGridSamplingDistance {
            get {
                return ((double)(this["AlgorithmGridSamplingDistance"]));
            }
            set {
                this["AlgorithmGridSamplingDistance"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50")]
        public int AlgorithmPRMSampleCount {
            get {
                return ((int)(this["AlgorithmPRMSampleCount"]));
            }
            set {
                this["AlgorithmPRMSampleCount"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4")]
        public int AlgorithmPRMNeighbourCount {
            get {
                return ((int)(this["AlgorithmPRMNeighbourCount"]));
            }
            set {
                this["AlgorithmPRMNeighbourCount"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("200")]
        public int AlgorithmRRTNeighbourCount {
            get {
                return ((int)(this["AlgorithmRRTNeighbourCount"]));
            }
            set {
                this["AlgorithmRRTNeighbourCount"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50")]
        public double AlgorithmRRTStepSize {
            get {
                return ((double)(this["AlgorithmRRTStepSize"]));
            }
            set {
                this["AlgorithmRRTStepSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.5")]
        public double AlgorithmRRTGoalBias {
            get {
                return ((double)(this["AlgorithmRRTGoalBias"]));
            }
            set {
                this["AlgorithmRRTGoalBias"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AlgorithmRRTStopAtGoal {
            get {
                return ((bool)(this["AlgorithmRRTStopAtGoal"]));
            }
            set {
                this["AlgorithmRRTStopAtGoal"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool DrawingShowConfigurationAtVertices {
            get {
                return ((bool)(this["DrawingShowConfigurationAtVertices"]));
            }
            set {
                this["DrawingShowConfigurationAtVertices"] = value;
            }
        }
    }
}
